[nfs]
172.31.33.122 ansible_ssh_user=ec2-user

[webservers]
172.31.36.123 ansible_ssh_user=ec2-user
172.31.39.209 ansible_ssh_user=ec2-user

[db]
172.31.37.173 ansible_ssh_user=ec2-user 

[lb]
172.31.46.217 ansible_ssh_user=ubuntu